### ISSUE TITLE
After timer started switching between modes is glitch

### ISSUE THREAD

**Issue by oacs** [NvChad/timerly#1]
Reproduce steps:
- start timer
- go to another mode

Expected behavior:
- It should be disabled to switch between modes if time is running or stop prev timer and made the switch

 

https://github.com/user-attachments/assets/f82a5b7f-3ea8-4deb-bd88-d4733fcc2b29

**Comment by siduck** [comment]
this isnt stable yet, i'll reset the timer when switching modes
